  name: Bedrock Server

  on:
    push:
      branches: [ main ]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Bedrock server
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.0.1.zip -O bedrock-server.zip
          unzip bedrock-server.zip -d bedrock-server
          chmod +x bedrock-server/bedrock_server
          cd bedrock-server
          ./bedrock_server
